name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      node-version: 20.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Get pnpm cache directory
        id: pnpm
        run: echo "::set-output name=dir::$(pnpm store path)"

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Test Build
        run: pnpm build
