name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.repository == 'Naturalclar/naturalclar.dev'

    env:
      node-version: 12.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1.4.0
        with:
          node-version: ${{ env.node-version }}

      - name: Get yarn cache directory
        id: yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ steps.yarn.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Add origin
        run: git remote add gh-pages git@github.com:Naturalclar/naturalclar.github.io.git

      - name: Echo origin
        run: git remote -v

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build Website
        run: yarn build
        
      - name: Prepare Deploy
        run: yarn export
      
      - name: echo "${GITHUB_ACTOR}"
        run: echo "${GITHUB_ACTOR}"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          echo "machine github.com login ${GITHUB_ACTOR} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          yarn deploy
