name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.repository == 'Naturalclar/naturalclar.dev'

    env:
      node-version: 20.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'

      - name: Add origin
        run: git remote add gh-pages https://github.com/Naturalclar/naturalclar.github.io.git

      - name: Echo origin
        run: git remote -v

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build Website
        run: pnpm build

      - name: Prepare Deploy
        run: pnpm export
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d out -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
